//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTX2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public long MaHoaDon { get; set; }
        public string ToaNha { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> SoNuoc { get; set; }
        public Nullable<int> SoDien { get; set; }
        public Nullable<System.DateTime> Thang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<long> NhanVienLap { get; set; }
    }
}
