//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTX2021
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyKTX2021Entities : DbContext
    {
        public QuanLyKTX2021Entities()
            : base("name=QuanLyKTX2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
    
        public virtual ObjectResult<Nullable<int>> DangNhap(Nullable<long> maSo, string matKhau)
        {
            var maSoParameter = maSo.HasValue ?
                new ObjectParameter("maSo", maSo) :
                new ObjectParameter("maSo", typeof(long));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("matKhau", matKhau) :
                new ObjectParameter("matKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DangNhap", maSoParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<LayDanhSachHoaDon_Result> LayDanhSachHoaDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachHoaDon_Result>("LayDanhSachHoaDon");
        }
    
        public virtual ObjectResult<LayDanhSachHopDong_Result> LayDanhSachHopDong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachHopDong_Result>("LayDanhSachHopDong");
        }
    
        public virtual ObjectResult<LayDanhSachNhanVien_Result> LayDanhSachNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachNhanVien_Result>("LayDanhSachNhanVien");
        }
    
        public virtual ObjectResult<LayDanhSachPhong_Result> LayDanhSachPhong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachPhong_Result>("LayDanhSachPhong");
        }
    
        public virtual ObjectResult<LayDanhSachSinhVien_Result> LayDanhSachSinhVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachSinhVien_Result>("LayDanhSachSinhVien");
        }
    
        public virtual ObjectResult<string> LayDanhSachTenPhong(string toaNha)
        {
            var toaNhaParameter = toaNha != null ?
                new ObjectParameter("toaNha", toaNha) :
                new ObjectParameter("toaNha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("LayDanhSachTenPhong", toaNhaParameter);
        }
    
        public virtual ObjectResult<string> LayDanhSachToaNha()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("LayDanhSachToaNha");
        }
    
        public virtual ObjectResult<Nullable<int>> SoNguoiHienTaiCuaPhong(string toaNha, string tenPhong)
        {
            var toaNhaParameter = toaNha != null ?
                new ObjectParameter("toaNha", toaNha) :
                new ObjectParameter("toaNha", typeof(string));
    
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("tenPhong", tenPhong) :
                new ObjectParameter("tenPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SoNguoiHienTaiCuaPhong", toaNhaParameter, tenPhongParameter);
        }
    
        public virtual int SuaHoaDon(Nullable<long> maHoaDon, string toaNha, string tenPhong, Nullable<int> soNuoc, Nullable<int> soDien, Nullable<System.DateTime> thang, Nullable<bool> trangThai, Nullable<decimal> tongTien, Nullable<long> nhanVienLap)
        {
            var maHoaDonParameter = maHoaDon.HasValue ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(long));
    
            var toaNhaParameter = toaNha != null ?
                new ObjectParameter("ToaNha", toaNha) :
                new ObjectParameter("ToaNha", typeof(string));
    
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("TenPhong", tenPhong) :
                new ObjectParameter("TenPhong", typeof(string));
    
            var soNuocParameter = soNuoc.HasValue ?
                new ObjectParameter("SoNuoc", soNuoc) :
                new ObjectParameter("SoNuoc", typeof(int));
    
            var soDienParameter = soDien.HasValue ?
                new ObjectParameter("SoDien", soDien) :
                new ObjectParameter("SoDien", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            var nhanVienLapParameter = nhanVienLap.HasValue ?
                new ObjectParameter("NhanVienLap", nhanVienLap) :
                new ObjectParameter("NhanVienLap", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaHoaDon", maHoaDonParameter, toaNhaParameter, tenPhongParameter, soNuocParameter, soDienParameter, thangParameter, trangThaiParameter, tongTienParameter, nhanVienLapParameter);
        }
    
        public virtual int SuaHopDong(Nullable<long> maHD, string maSV, string tenSV, string toaNha, string tenPhong, Nullable<System.DateTime> ngayLap, Nullable<System.DateTime> ngayHetHan, Nullable<decimal> tienPhong, Nullable<long> nhanVienLap)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(long));
    
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var tenSVParameter = tenSV != null ?
                new ObjectParameter("TenSV", tenSV) :
                new ObjectParameter("TenSV", typeof(string));
    
            var toaNhaParameter = toaNha != null ?
                new ObjectParameter("ToaNha", toaNha) :
                new ObjectParameter("ToaNha", typeof(string));
    
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("TenPhong", tenPhong) :
                new ObjectParameter("TenPhong", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var ngayHetHanParameter = ngayHetHan.HasValue ?
                new ObjectParameter("NgayHetHan", ngayHetHan) :
                new ObjectParameter("NgayHetHan", typeof(System.DateTime));
    
            var tienPhongParameter = tienPhong.HasValue ?
                new ObjectParameter("TienPhong", tienPhong) :
                new ObjectParameter("TienPhong", typeof(decimal));
    
            var nhanVienLapParameter = nhanVienLap.HasValue ?
                new ObjectParameter("NhanVienLap", nhanVienLap) :
                new ObjectParameter("NhanVienLap", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaHopDong", maHDParameter, maSVParameter, tenSVParameter, toaNhaParameter, tenPhongParameter, ngayLapParameter, ngayHetHanParameter, tienPhongParameter, nhanVienLapParameter);
        }
    
        public virtual int SuaNhanVien(string hoTen, Nullable<long> cmnd, string queQuan, string congViec, Nullable<long> luong, string diaDiem, Nullable<long> sdt)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var cmndParameter = cmnd.HasValue ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(long));
    
            var queQuanParameter = queQuan != null ?
                new ObjectParameter("queQuan", queQuan) :
                new ObjectParameter("queQuan", typeof(string));
    
            var congViecParameter = congViec != null ?
                new ObjectParameter("congViec", congViec) :
                new ObjectParameter("congViec", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(long));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("diaDiem", diaDiem) :
                new ObjectParameter("diaDiem", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNhanVien", hoTenParameter, cmndParameter, queQuanParameter, congViecParameter, luongParameter, diaDiemParameter, sdtParameter);
        }
    
        public virtual int SuaPhong(string toaNha, string tenPhong, string loaiPhong, Nullable<int> soNguoiToiDa)
        {
            var toaNhaParameter = toaNha != null ?
                new ObjectParameter("toaNha", toaNha) :
                new ObjectParameter("toaNha", typeof(string));
    
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("tenPhong", tenPhong) :
                new ObjectParameter("tenPhong", typeof(string));
    
            var loaiPhongParameter = loaiPhong != null ?
                new ObjectParameter("loaiPhong", loaiPhong) :
                new ObjectParameter("loaiPhong", typeof(string));
    
            var soNguoiToiDaParameter = soNguoiToiDa.HasValue ?
                new ObjectParameter("soNguoiToiDa", soNguoiToiDa) :
                new ObjectParameter("soNguoiToiDa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaPhong", toaNhaParameter, tenPhongParameter, loaiPhongParameter, soNguoiToiDaParameter);
        }
    
        public virtual int SuaSinhVien(string maSV, string tenSV, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, Nullable<long> cMND, string queQuan, string danToc, string lop, Nullable<long> sDT, string tenPhuHuynh, string sDTPhuHuynh)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var tenSVParameter = tenSV != null ?
                new ObjectParameter("TenSV", tenSV) :
                new ObjectParameter("TenSV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var cMNDParameter = cMND.HasValue ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(long));
    
            var queQuanParameter = queQuan != null ?
                new ObjectParameter("QueQuan", queQuan) :
                new ObjectParameter("QueQuan", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var lopParameter = lop != null ?
                new ObjectParameter("Lop", lop) :
                new ObjectParameter("Lop", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(long));
    
            var tenPhuHuynhParameter = tenPhuHuynh != null ?
                new ObjectParameter("TenPhuHuynh", tenPhuHuynh) :
                new ObjectParameter("TenPhuHuynh", typeof(string));
    
            var sDTPhuHuynhParameter = sDTPhuHuynh != null ?
                new ObjectParameter("SDTPhuHuynh", sDTPhuHuynh) :
                new ObjectParameter("SDTPhuHuynh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaSinhVien", maSVParameter, tenSVParameter, ngaySinhParameter, gioiTinhParameter, cMNDParameter, queQuanParameter, danTocParameter, lopParameter, sDTParameter, tenPhuHuynhParameter, sDTPhuHuynhParameter);
        }
    
        public virtual int ThemHoaDon(string toaNha, string tenPhong, Nullable<int> soNuoc, Nullable<int> soDien, Nullable<System.DateTime> thang, Nullable<bool> trangThai, Nullable<decimal> tongTien, Nullable<long> nhanVienLap)
        {
            var toaNhaParameter = toaNha != null ?
                new ObjectParameter("ToaNha", toaNha) :
                new ObjectParameter("ToaNha", typeof(string));
    
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("TenPhong", tenPhong) :
                new ObjectParameter("TenPhong", typeof(string));
    
            var soNuocParameter = soNuoc.HasValue ?
                new ObjectParameter("SoNuoc", soNuoc) :
                new ObjectParameter("SoNuoc", typeof(int));
    
            var soDienParameter = soDien.HasValue ?
                new ObjectParameter("SoDien", soDien) :
                new ObjectParameter("SoDien", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            var nhanVienLapParameter = nhanVienLap.HasValue ?
                new ObjectParameter("NhanVienLap", nhanVienLap) :
                new ObjectParameter("NhanVienLap", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemHoaDon", toaNhaParameter, tenPhongParameter, soNuocParameter, soDienParameter, thangParameter, trangThaiParameter, tongTienParameter, nhanVienLapParameter);
        }
    
        public virtual int ThemHopDong(string maSV, string tenSV, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, Nullable<long> cMND, string queQuan, string danToc, string lop, string toaNha, string tenPhong, Nullable<long> sDT, string matKhau, string tenPhuHuynh, string sDTPhuHuynh, Nullable<System.DateTime> ngayLap, Nullable<System.DateTime> ngayHetHan, Nullable<decimal> tienPhong, Nullable<long> nhanVienLap)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var tenSVParameter = tenSV != null ?
                new ObjectParameter("TenSV", tenSV) :
                new ObjectParameter("TenSV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var cMNDParameter = cMND.HasValue ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(long));
    
            var queQuanParameter = queQuan != null ?
                new ObjectParameter("QueQuan", queQuan) :
                new ObjectParameter("QueQuan", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var lopParameter = lop != null ?
                new ObjectParameter("Lop", lop) :
                new ObjectParameter("Lop", typeof(string));
    
            var toaNhaParameter = toaNha != null ?
                new ObjectParameter("ToaNha", toaNha) :
                new ObjectParameter("ToaNha", typeof(string));
    
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("TenPhong", tenPhong) :
                new ObjectParameter("TenPhong", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(long));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var tenPhuHuynhParameter = tenPhuHuynh != null ?
                new ObjectParameter("TenPhuHuynh", tenPhuHuynh) :
                new ObjectParameter("TenPhuHuynh", typeof(string));
    
            var sDTPhuHuynhParameter = sDTPhuHuynh != null ?
                new ObjectParameter("SDTPhuHuynh", sDTPhuHuynh) :
                new ObjectParameter("SDTPhuHuynh", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var ngayHetHanParameter = ngayHetHan.HasValue ?
                new ObjectParameter("NgayHetHan", ngayHetHan) :
                new ObjectParameter("NgayHetHan", typeof(System.DateTime));
    
            var tienPhongParameter = tienPhong.HasValue ?
                new ObjectParameter("TienPhong", tienPhong) :
                new ObjectParameter("TienPhong", typeof(decimal));
    
            var nhanVienLapParameter = nhanVienLap.HasValue ?
                new ObjectParameter("NhanVienLap", nhanVienLap) :
                new ObjectParameter("NhanVienLap", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemHopDong", maSVParameter, tenSVParameter, ngaySinhParameter, gioiTinhParameter, cMNDParameter, queQuanParameter, danTocParameter, lopParameter, toaNhaParameter, tenPhongParameter, sDTParameter, matKhauParameter, tenPhuHuynhParameter, sDTPhuHuynhParameter, ngayLapParameter, ngayHetHanParameter, tienPhongParameter, nhanVienLapParameter);
        }
    
        public virtual int ThemNhanVien(string hoTen, Nullable<long> cmnd, string queQuan, string congViec, Nullable<long> luong, string diaDiem, Nullable<long> sdt, string matKhau)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var cmndParameter = cmnd.HasValue ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(long));
    
            var queQuanParameter = queQuan != null ?
                new ObjectParameter("queQuan", queQuan) :
                new ObjectParameter("queQuan", typeof(string));
    
            var congViecParameter = congViec != null ?
                new ObjectParameter("congViec", congViec) :
                new ObjectParameter("congViec", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(long));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("diaDiem", diaDiem) :
                new ObjectParameter("diaDiem", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(long));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("matKhau", matKhau) :
                new ObjectParameter("matKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNhanVien", hoTenParameter, cmndParameter, queQuanParameter, congViecParameter, luongParameter, diaDiemParameter, sdtParameter, matKhauParameter);
        }
    
        public virtual int ThemPhong(string toaNha, string tenPhong, string loaiPhong, Nullable<int> soNguoiToiDa)
        {
            var toaNhaParameter = toaNha != null ?
                new ObjectParameter("toaNha", toaNha) :
                new ObjectParameter("toaNha", typeof(string));
    
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("tenPhong", tenPhong) :
                new ObjectParameter("tenPhong", typeof(string));
    
            var loaiPhongParameter = loaiPhong != null ?
                new ObjectParameter("loaiPhong", loaiPhong) :
                new ObjectParameter("loaiPhong", typeof(string));
    
            var soNguoiToiDaParameter = soNguoiToiDa.HasValue ?
                new ObjectParameter("soNguoiToiDa", soNguoiToiDa) :
                new ObjectParameter("soNguoiToiDa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemPhong", toaNhaParameter, tenPhongParameter, loaiPhongParameter, soNguoiToiDaParameter);
        }
    
        public virtual ObjectResult<TimHopDong_Result> TimHopDong(Nullable<long> maHD, string tenSV)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(long));
    
            var tenSVParameter = tenSV != null ?
                new ObjectParameter("tenSV", tenSV) :
                new ObjectParameter("tenSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimHopDong_Result>("TimHopDong", maHDParameter, tenSVParameter);
        }
    
        public virtual ObjectResult<TimHopDongTheoMaHD_Result> TimHopDongTheoMaHD(Nullable<long> maHD)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimHopDongTheoMaHD_Result>("TimHopDongTheoMaHD", maHDParameter);
        }
    
        public virtual int XoaHoaDon(Nullable<long> maHoaDon)
        {
            var maHoaDonParameter = maHoaDon.HasValue ?
                new ObjectParameter("maHoaDon", maHoaDon) :
                new ObjectParameter("maHoaDon", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaHoaDon", maHoaDonParameter);
        }
    
        public virtual int XoaHopDong(Nullable<long> maHD)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("maHD", maHD) :
                new ObjectParameter("maHD", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaHopDong", maHDParameter);
        }
    
        public virtual int XoaNhanVien(Nullable<long> cmnd)
        {
            var cmndParameter = cmnd.HasValue ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNhanVien", cmndParameter);
        }
    
        public virtual int XoaPhong(string toaNha, string tenPhong)
        {
            var toaNhaParameter = toaNha != null ?
                new ObjectParameter("toaNha", toaNha) :
                new ObjectParameter("toaNha", typeof(string));
    
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("tenPhong", tenPhong) :
                new ObjectParameter("tenPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaPhong", toaNhaParameter, tenPhongParameter);
        }
    
        public virtual ObjectResult<TimPhong_Result> TimPhong(string tenPhong)
        {
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("tenPhong", tenPhong) :
                new ObjectParameter("tenPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimPhong_Result>("TimPhong", tenPhongParameter);
        }
    }
}
